id: I5D8DE4D6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-04-06T07:13:21+00:00'
last_modified: '2022-06-13T12:50:38.839288+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7000
  title: ཏུན་ཧོང་ཤོག་ཧྲིལ་ཡིག་རྙིང་གི་བཤུས་ཡིག་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    299D:
      image_group_id: I3CN7002
      title: ''
      total_pages: ''
      order: 1
      base_file: 299D.txt
    2C36:
      image_group_id: I3CN7003
      title: ''
      total_pages: ''
      order: 2
      base_file: 2C36.txt
    1CE8:
      image_group_id: I3CN7004
      title: ''
      total_pages: ''
      order: 3
      base_file: 1CE8.txt
    227E:
      image_group_id: I3CN7005
      title: ''
      total_pages: ''
      order: 4
      base_file: 227E.txt
    5C36:
      image_group_id: I3CN7006
      title: ''
      total_pages: ''
      order: 5
      base_file: 5C36.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
