id: opecha:P000817
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN7000
  title: ཏུན་ཧོང་ཤོག་ཧྲིལ་ཡིག་རྙིང་གི་བཤུས་ཡིག་ཕྱོགས་བསྒྲིགས།
  volumes:
    31c8222ca169494ab4b6ab8c5fa415b9:
      image_group_id: I3CN7002
      title: ''
      base_file: v001.txt
    d17a7f1378d84b2c9b8649af219eafe9:
      image_group_id: I3CN7003
      title: ''
      base_file: v002.txt
    8d23323d2ea14b64bdf9958128bec532:
      image_group_id: I3CN7004
      title: ''
      base_file: v003.txt
    919fcc8305be448580113f714a81b603:
      image_group_id: I3CN7005
      title: ''
      base_file: v004.txt
    c07d515b68964ff6b9bf84d1ba582644:
      image_group_id: I3CN7006
      title: ''
      base_file: v005.txt
  author: ''
